import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 600px;
    height: 250px;
    title: "Njord a Bitcoin Price Fetcher";
    icon: @image-url("icons/bitcoin-logo.png");
    in-out property <string> price: 0;
    in-out property <string> time: 0;
    callback request-increase-value();
    VerticalBox {
        spacing: 4px;
        VerticalLayout {
            alignment: center;
            spacing: 40px;

            HorizontalLayout {
                HorizontalLayout {
                    spacing: 40px;
                    Image {
                        source: @image-url("icons/bitcoin-logo.png");
                        width: 64px;
                    }

                    Text {
                        font-size: 36px;
                        text: "BTC Price";
                        vertical-alignment: center;
                    }
                }

                Text {
                    font-size: 36px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: "$ \{root.price}";
                }
            }

                Button {
                    accessible-role: AccessibleRole.none;
                    height: 60px;
                    primary: true;
                    text: "Refresh";
                    clicked => {
                        root.request-increase-value();
                    }
                }

                Text {
                    font-size: 24px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: "Last refresh: \{root.time}";
                }
        }
    }
}
